# Generated by Django 5.1.5 on 2025-02-04 14:52

import siteapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=255)),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('job_title', models.CharField(max_length=255)),
                ('qualification', models.CharField(max_length=255)),
                ('cv', models.FileField(upload_to=siteapp.models.cv_upload_path)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
